languageCode = "en-us"
title = "Lucia Darrow"
baseURL = "http://localhost:1313/"
theme = "hugo-theme-massively"
SectionPagesMenu ="main"
googleanalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section"]

# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"
  # set to change date format
  # dateFormat = "2.1.2006"

# Below parameters can be set to override default post settings
# [params.posts]
#     folderName = "post"
#     pageSize = "6"
#     featuredPost = true
#     paginationPages = 2
#     showFirstLast = false

[languages]
[languages.en]
  languageName = "English"

[params.posts]
    foldername = "post"
    pagesize = "6"
    featuredpost= "true"

[menu]
    [[menu.main]]
  	name="Home"
  	identifier="home"
  	url="/"
	  weight=1

   [[menu.main]]
  	name="About"
  	identifier="about"
  	url="/about/"
	  weight=2



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
